<a href="https://colab.research.google.com/github/Enkhzol/diveintocode-ml/blob/master/diver_class_assignment6_ML_preclass_matrix_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**[Problem 1] Matrix product is calculated manually**

In [ ]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

Each two-dimensional matrix contains three one-dimensional matrices that 1D matrix also consists of 3 elements.

**[Problem 2] Calculation by NumPy function**

row of matrix A X column of matrix B

-1 * 0 + 2 * 0 + 3 * 2 = 6 is written [[**6** , ?, ?][? , ?, ?][? , ?, ?]] 

-1 * 2 + 2 * 2 + 3 * 9 = 29 is written [[6 , **29**, ?][? , ?, ?][? , ?, ?]]

The following multiplication are similar.

In [ ]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

c_ndarray = np.matmul(a_ndarray, b_ndarray)
print(c_ndarray)

d_ndarray = np.dot(a_ndarray, b_ndarray)
print(d_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


**[Problem 3] Implementation of calculation of a certain element**

In [19]:
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

c_ndarray = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]])

for i in range(len(a_ndarray)):
   for j in range(len(b_ndarray[0])):
       for k in range(len(b_ndarray)):
           c_ndarray[i][j] += a_ndarray[i][k] * b_ndarray[k][j]

print(c_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


**[Problem 4] Creating a function that performs matrix multiplication**

In [32]:
import numpy as np

def mul_matrices(a, b):
  c = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]])

  for i in range(len(a)):
    for j in range(len(b[0])):
        for k in range(len(b)):
            c[i][j] += a[i][k] * b[k][j]
  return c

d_ndarray_ = np.array([[-1, 2, 3], [4, -5, 6], [0, 0, 0]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4], [0, 0, 0]])

c1 = mul_matrices(d_ndarray_, e_ndarray)
print(c1)


[[ 21 -18   1]
 [-66  57   8]
 [  0   0   0]]


**[Problem 5] Judge the input whose calculation is not defined**

In [36]:
import numpy as np

def mul_matrices(a, b):
  c = np.array([[0, 0, 0], [0, 0, 0]])

  for i in range(len(a)):
    for j in range(len(b[0])):
        for k in range(len(b)):
            c[i][j] += a[i][k] * b[k][j]
  return c

d_ndarray_ = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

c1 = mul_matrices(d_ndarray_, e_ndarray)
print(c1)

[[ 21 -18   1]
 [-66  57   8]]


**[Problem 6] Transposition**

In [43]:
import numpy as np

def mul_matrices(a, b):
  c = np.array([[0, 0, 0], [0, 0, 0]])

  for i in range(len(a)):
    for j in range(len(b[0])):
        for k in range(len(b)):
            c[i][j] += a[i][k] * b[k][j]
  return c

d_ndarray_ = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
#e_ndarray = np.transpose(e_ndarray)
e_ndarray = e_ndarray.T
print(e_ndarray)

c1 = mul_matrices(d_ndarray_, e_ndarray)
print(c1)

[[-9  6]
 [ 8 -5]
 [ 7  4]]
[[ 46  -4   0]
 [-34  73   0]]
