<a href="https://colab.research.google.com/github/Enkhzol/diveintocode-ml/blob/master/diver_class_assignment13_UtilizationObjectOrientation_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**[Problem 1] Enumeration of classes used so far**

In [1]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scaler = StandardScaler()
scaler.fit(X)
print("Mean :", scaler.mean_)
print("Variance :", scaler.var_)
X_std = scaler.transform(X)

Mean : [4.86 3.31 1.45 0.22]
Variance : [0.0764 0.0849 0.0105 0.0056]


In [2]:
# Pandas
import pandas as pd
import inspect

classes = list(map(lambda x:x[0], inspect.getmembers(pd, inspect.isclass)))
classes[:5]

['BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame']

In [3]:
# matplotlib
import matplotlib
classes = list(map(lambda x:x[0], inspect.getmembers(matplotlib, inspect.isclass)))
classes[:5]

['ExecutableNotFoundError',
 'LooseVersion',
 'MatplotlibDeprecationWarning',
 'MutableMapping',
 'Parameter']

In [4]:
# Show all methods
dir(scaler)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_reset',
 'copy',
 'fit',
 'fit_transform',
 'get_params',
 'inverse_transform',
 'mean_',
 'n_samples_seen_',
 'partial_fit',
 'scale_',
 'set_params',
 'transform',
 'var_',
 'with_mean',
 'with_std']

**[Problem 2] Enumeration of methods and instance variables used so far**

Method:

* ndarray.sum()
* pandas.DataFrame.groupby()
* range()
* zip()
* matplotlib.pyplot.scatter

Instance variables:
* ndarray.shape
* pandas.DataFrame.columns
* pandas.DataFrame.index
* ndarray.dtype
* ndarray.T

**[Problem 3] Creating a standardized class by scratch**

In [5]:
class ScratchStandardScaler():
    """
    Class for standardization

    Attributes

    mean_: ndarray, shape (n_features,) of the following form
    average

    var_: ndarray, shape (n_features,) of the following form
    Distributed
    """
    def fit(self, X):
        """
        Calculate the mean and standard deviation for standardization.

        Parameters

        X: ndarray, shape (n_samples, n_features) of the following form
        Training data
        """
        self.mean_ = X.mean(axis=0)
        self.var_ = X.var(axis=0)
        
    def transform(self, X):
        """
       Standardize using the value obtained by fit.

        Parameters

        X: ndarray, shape (n_samples, n_features) of the following form
        Feature value

        Returns

        X_scaled: ndarray, shape (n_samples, n_features) of the following form
        Standardized special amount
        """
        # Explanatory variable-mean of that column / square root of standard deviation of each column
        X_scaled = (X - self.mean_) / np.sqrt(self.var_)
        return X_scaled

In [6]:
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("Mean :", scratch_scaler.mean_)
print("Vanriance :", scratch_scaler.var_)
X_std = scratch_scaler.transform(X)
print(X_std)

print('X_std mean: {:.1f}, variance: {:.1f}'.format(X_std.mean(), X_std.var()))

Mean : [4.86 3.31 1.45 0.22]
Vanriance : [0.0764 0.0849 0.0105 0.0056]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]
X_std mean: 0.0, variance: 1.0


In [7]:
# Compare with Standard library
scaler = StandardScaler()
scaler.fit(X)
print("Mean :", scaler.mean_)
print("Vanriance :", scaler.var_)
X_std = scaler.transform(X)
print(X_std)
print('X_std mean: {:.1f}, variance: {:.1f}'.format(X_std.mean(), X_std.var()))

Mean : [4.86 3.31 1.45 0.22]
Vanriance : [0.0764 0.0849 0.0105 0.0056]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]
X_std mean: 0.0, variance: 1.0


**[Problem 4] Creating a class that performs 4 arithmetic operations**

The above ExampleClass has an addition method, but please add subtraction, multiplication, and division methods to it.


If the value entered into the constructor is a non-numeric value such as a string or an array, an error should be raised.


The class name and description should also be rewritten appropriately.

In [8]:
class ArithmeticOperation():
    def __init__(self, value):
        assert type(value) in [int,float], "Please input Int or Float"
        self.value = value
        print("The initial value {} has been set".format(self.value))
    def add(self, value):
        """
        Add the received argument to self.value
        """
        assert type(value) in [int,float], "Please input Int or Float"
        self.value += value

    def sub(self, value):
        """
        Subtract the received argument to self.value
        """
        assert type(value) in [int,float], "Please input Int or Float"
        self.value -= value
    def mul(self, value):
        """
        Multiply the received argument to self.value
        """
        assert type(value) in [int,float], "Please input Int or Float"
        self.value *= value

    def div(self, value):
        """
        Divide the received argument to self.value
        """
        assert type(value) in [int,float], "Please input Int or Float"
        self.value /= value

example = ArithmeticOperation(5)

print("value+3: {}".format(example.value))
example.sub(4)
print("value-4: {}".format(example.value))
example.mul(2)
print("value*2: {}".format(example.value))
example.div(3)
print("value/3: {}".format(example.value))

The initial value 5 has been set
value+3: 5
value-4: 1
value*2: 2
value/3: 0.6666666666666666
