<a href="https://colab.research.google.com/github/Enkhzol/diveintocode-ml/blob/master/Sprint2_Intro_ML_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. About this Sprint​ ​**

The purpose of this Sprint

    Prepare for machine learning scratch


How to learn

First, use scikit-learn to implement a machine learning program that will be implemented by scratch in future learning.


**2. What is scratch? **

By combining the basic libraries provided in NumPy etc., you can create your own classes / functions equivalent to the functions implemented in the applied libraries such as scikit-learn. This is called scratch.​

Through scratching, it is difficult to grasp just by moving a library such as scikit-learn, and we aim for a deep understanding of the algorithm. It also improves your coding skills, but that's not the main purpose.

We are aiming for the following effects.

    Make it easier to understand theory and mathematical formulas when encountering new methods
    Reduce ambiguity in using libraries
    Make existing implementations easier to read


This time, first, we will implement the machine learning program using scikit-learn without completely scratching it. Then, from the next time, we will gradually shift the implementation using scikit-learn to scratch.


**[Problem 1] Scratch of train_test_split​**

First, try scratching train_test_split of scikit-learn. Please implement the function based on the following template.

https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html

Be sure to check if the created function train_test_split​

 Prototype
 

def scratch_train_test_split(X, y, train_size=0.8):
    """Divide the validation data.
    Parameters
    ----------
    X : ndarray
      Training data (n_samples, n_features)
    y : ndarray
      Correct answer value (n_samples,)
    train_size : float
      Specify what percentage to use as a train (0 < train_size < 1)
    Returns
    -------
    X_train : ndarray
      Training data (n_samples, n_features)
    X_test : ndarray
      Validation data (n_samples, n_features)
    y_train : ndarray
      Correct answer value of training data (n_samples,)
    y_test : ndarray
      Correct value of verification data (n_samples,)
    """
    # Write code here
    pass
    return X_train, X_test, y_train, y_test

In [2]:
import pandas as pd
import numpy as np

def scratch_train_test_split(X, y, test_size=0.3, random_state = 0):
    n_samples = X.shape[0]

    #floor is devaluated 
    n_train = np.floor((1-test_size) * n_samples).astype(int)
    n_test = n_samples - n_train
    
    rng = np.random.RandomState(seed=random_state)
    #n_samples(Randomly arrange 100 rows of X (0 to 99))
    permutation = rng.permutation(n_samples)
    
    #Randomly arranged n_samples are selected from the top of n_test
    ind_test = permutation[:n_test]
    
    #If it is n_samples, it will be an error 0 ~ 99
    ind_train = permutation[n_test:(n_test + n_train)]
    
    #X[[2,5,86,45,0]]←The line below looks like this
    X_train = X[ind_train]
    X_test = X[ind_test]
    y_train = y[ind_train]
    y_test = y[ind_test]
    
    return X_train, X_test, y_train, y_test

3. Implementation of code for machine learning using scikit-learn

We will implement the code using scikit-learn to create a baseline model.

Use the self-made function created in question 1 to divide the verification data. The hold out method may be used instead of cross Validation.

Classification problem

The classification is implemented using scikit-learn for three different methods.

    Logistic regression
    SVM
    Decision tree


It can be used in scikit-learn from two types, LogisticRegression class and SGDClassifier class. Here, use the SGDClassifier class that calculates using the gradient descent method. Logistic regression can be calculated by setting loss = ”log” as an argument.

The scikit-learn as a classifier that can be used in logistic regression LogisticRegression class and SGDClassifier have classes are available. SGDClassifier class, which is calculated using the gradient descent method. Logistic regression can be calculated by specifying loss="log" as an argument.

https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.SGDClassifier.html#sklearn.linear_model.SGDClassifier

https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html#sklearn.svm.SVC

https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html#sklearn.tree.DecisionTreeClassifier



Check the operation using three types of data sets.

The first is the iris dataset similar to the pre-learning period.

sklearn.datasets.load_iris - scikit-learn stable version documentation:
https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_iris.html

Since we want to make a binary classification, we will use only the following two objective variables. All four types of features are used.

    virgicolor and virginica


The other two are artificial datasets with two feature values. With the following code we can create the explanatory variableXand the objective variable y. Let's call them "Simple Data Set 1" and "Simple Data Set 2". As there are only two features, visualization is easy.

Simple data set 1 creation code

In [ ]:
import numpy as np
np.random.seed(seed=0)
n_samples = 500
f0 = [-1, 2]
f1 = [2, -1]
cov = [[1.0,0.8], [0.8, 1.0]]
f0 = np.random.multivariate_normal(f0, cov, n_samples // 2)
f1 = np.random.multivariate_normal(f1, cov, n_samples // 2)
X = np.concatenate([f0, f1])
y = np.concatenate([
    np.full(n_samples // 2, 1),
    np.full(n_samples // 2, -1)
])

**Simple data set 2 creation code**

In [ ]:
X = np.array([
    [-0.44699 , -2.8073  ],[-1.4621  , -2.4586  ],
    [ 0.10645 ,  1.9242  ],[-3.5944  , -4.0112  ],
    [-0.9888  ,  4.5718  ],[-3.1625  , -3.9606  ],
    [ 0.56421 ,  0.72888 ],[-0.60216 ,  8.4636  ],
    [-0.61251 , -0.75345 ],[-0.73535 , -2.2718  ],
    [-0.80647 , -2.2135  ],[ 0.86291 ,  2.3946  ],
    [-3.1108  ,  0.15394 ],[-2.9362  ,  2.5462  ],
    [-0.57242 , -2.9915  ],[ 1.4771  ,  3.4896  ],
    [ 0.58619 ,  0.37158 ],[ 0.6017  ,  4.3439  ],
    [-2.1086  ,  8.3428  ],[-4.1013  , -4.353   ],
    [-1.9948  , -1.3927  ],[ 0.35084 , -0.031994],
    [ 0.96765 ,  7.8929  ],[-1.281   , 15.6824  ],
    [ 0.96765 , 10.083   ],[ 1.3763  ,  1.3347  ],
    [-2.234   , -2.5323  ],[-2.9452  , -1.8219  ],
    [ 0.14654 , -0.28733 ],[ 0.5461  ,  5.8245  ],
    [-0.65259 ,  9.3444  ],[ 0.59912 ,  5.3524  ],
    [ 0.50214 , -0.31818 ],[-3.0603  , -3.6461  ],
    [-6.6797  ,  0.67661 ],[-2.353   , -0.72261 ],
    [ 1.1319  ,  2.4023  ],[-0.12243 ,  9.0162  ],
    [-2.5677  , 13.1779  ],[ 0.057313,  5.4681  ],
])
y = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

**[Problem 2] Creating a code to solve the classification problem**

Create code to train and estimate 3 types of datasets using the 3 types of methods above.

Regression problem

Next, we will implement one type of regression using scikit-learn.

    Linear regression


For linear regression, use SGDRegressor class, which is calculated using gradient descent.

sklearn.linear_model.SGDRegressor - scikit-lear stable version documentation
https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.SGDRegressor.html

The data set is from the House Prices competition as in the pre-study period.

House Prices: Advanced Regression Techniques
https://www.kaggle.com/c/house-prices-advanced-regression-techniques/data

Downloadtrain.csvand use SalePriceas the objective variable andGrLivAreaand YearBuiltas the explanatory variables.

**Logistic regression**

In [5]:
from sklearn.datasets import load_iris
iris = load_iris()

X = iris.data[50:, :3]
y = iris.target[50:]

X_train, X_test, y_train, y_test = scratch_train_test_split(X, y, test_size =0.3, random_state=0)

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_std = sc.fit_transform(X_train)

#検証用のデータにtransformを行います。
X_test_std = sc.transform(X_test)

from sklearn.linear_model import SGDClassifier
from sklearn.pipeline import make_pipeline
# sgdc = make_pipeline(StandardScaler(),SGDClassifier(loss ='log'))
# sgdc.fit(X_train, y_train)
# Y_pred = sgdc.predict(X_test)

sgdc = SGDClassifier(loss='log')
sgdc.fit(X_std, y_train)
Y_pred = sgdc.predict(X_test_std)

from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix


print('accuracy = {}'.format(accuracy_score(y_test, Y_pred)))
print('precision = {}'.format(precision_score(y_test, Y_pred)))
print('recall = {}'.format(recall_score(y_test, Y_pred)))
print('f1 score = {}'.format(f1_score(y_test, Y_pred)))
print('confusion matrix = \n{}'.format(confusion_matrix(y_test, Y_pred)))

accuracy = 0.9
precision = 0.9285714285714286
recall = 0.8666666666666667
f1 score = 0.896551724137931
confusion matrix = 
[[13  2]
 [ 1 14]]


**SVM**

In [6]:
import numpy as np
np.random.seed(seed=0)
n_samples = 500
f0 = [-1, 2]
f1 = [2, -1]
cov = [[1.0,0.8], [0.8, 1.0]]
f0 = np.random.multivariate_normal(f0, cov, int(n_samples/2))
f1 = np.random.multivariate_normal(f1, cov, int(n_samples/2))
X = np.concatenate((f0, f1))
y = np.concatenate((np.ones((int(n_samples/2))), np.ones((int(n_samples/2))) *(-1))).astype(np.int)
random_index = np.random.permutation(np.arange(n_samples))
X = X[random_index]
y = y[random_index]

X_train, X_test, y_train, y_test = scratch_train_test_split(X, y, test_size =0.3, random_state=0)

from sklearn.svm import SVC

svm = make_pipeline(StandardScaler(), SVC(gamma='auto'))
svm.fit(X_train, y_train)
Y_pred = svm.predict(X_test)

print('accuracy = {}'.format(accuracy_score(y_test, Y_pred)))
print('precision = {}'.format(precision_score(y_test, Y_pred)))
print('recall = {}'.format(recall_score(y_test, Y_pred)))
print('f1 score = {}'.format(f1_score(y_test, Y_pred)))
print('confusion matrix = \n{}'.format(confusion_matrix(y_test, Y_pred)))

accuracy = 1.0
precision = 1.0
recall = 1.0
f1 score = 1.0
confusion matrix = 
[[65  0]
 [ 0 85]]


**Decision tree**

In [7]:
X = np.array([[-0.44699 , -2.8073  ],[-1.4621  , -2.4586  ],
       [ 0.10645 ,  1.9242  ],[-3.5944  , -4.0112  ],
       [-0.9888  ,  4.5718  ],[-3.1625  , -3.9606  ],
       [ 0.56421 ,  0.72888 ],[-0.60216 ,  8.4636  ],
       [-0.61251 , -0.75345 ],[-0.73535 , -2.2718  ],
       [-0.80647 , -2.2135  ],[ 0.86291 ,  2.3946  ],
       [-3.1108  ,  0.15394 ],[-2.9362  ,  2.5462  ],
       [-0.57242 , -2.9915  ],[ 1.4771  ,  3.4896  ],
       [ 0.58619 ,  0.37158 ],[ 0.6017  ,  4.3439  ],
       [-2.1086  ,  8.3428  ],[-4.1013  , -4.353   ],
       [-1.9948  , -1.3927  ],[ 0.35084 , -0.031994],
       [ 0.96765 ,  7.8929  ],[-1.281   , 15.6824  ],
       [ 0.96765 , 10.083   ],[ 1.3763  ,  1.3347  ],
       [-2.234   , -2.5323  ],[-2.9452  , -1.8219  ],
       [ 0.14654 , -0.28733 ],[ 0.5461  ,  5.8245  ],
       [-0.65259 ,  9.3444  ],[ 0.59912 ,  5.3524  ],
       [ 0.50214 , -0.31818 ],[-3.0603  , -3.6461  ],
       [-6.6797  ,  0.67661 ],[-2.353   , -0.72261 ],
       [ 1.1319  ,  2.4023  ],[-0.12243 ,  9.0162  ],
       [-2.5677  , 13.1779  ],[ 0.057313,  5.4681  ]])
y = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

X_train, X_test, y_train, y_test = scratch_train_test_split(X, y, test_size =0.3, random_state=0)

from sklearn.tree import DecisionTreeClassifier

clf = DecisionTreeClassifier(random_state=0)

clf = DecisionTreeClassifier()
clf.fit(X_train, y_train)
Y_pred = clf.predict(X_test)

print('accuracy = {}'.format(accuracy_score(y_test, Y_pred)))
print('precision = {}'.format(precision_score(y_test, Y_pred)))
print('recall = {}'.format(recall_score(y_test, Y_pred)))
print('f1 score = {}'.format(f1_score(y_test, Y_pred)))
print('confusion matrix = \n{}'.format(confusion_matrix(y_test, Y_pred)))

accuracy = 0.8333333333333334
precision = 0.8571428571428571
recall = 0.8571428571428571
f1 score = 0.8571428571428571
confusion matrix = 
[[4 1]
 [1 6]]


**[Problem 3] Creating a code to solve the regression problem**

Create code to train and estimate the House Prices data set with linear regression.

In [15]:
df_train = pd.read_csv('/content/drive/MyDrive/my_sample_data/HousePricesData/train.csv')

df = df_train.loc[:, ['GrLivArea','YearBuilt', 'SalePrice']]

df1 = np.log(df)

**Linear regression**

In [17]:
X_train, X_test, y_train, y_test = scratch_train_test_split(np.array(df1.iloc[:, [0, 1]]), np.array(df1.iloc[:, [2]]), random_state = 0)
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

lr = LinearRegression()

#Training with linear regression
lr.fit(X_train, y_train)

#Predicting
Y_pred = lr.predict(X_test)

from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

print ('mean absolute error (MAE) = {}'.format(mean_absolute_error(y_test, Y_pred)))
print ('Mean squared error (MSE) = {}'.format(mean_squared_error(y_test, Y_pred)))
print ('Root mean square error (RMSE) = {}'.format(np.sqrt(mean_squared_error (y_test, Y_pred))))
print ('coefficient of determination (R2) = {}'.format(r2_score(y_test, Y_pred)))

mean absolute error (MAE) = 0.15353180375096695
Mean squared error (MSE) = 0.04439252334052215
Root mean square error (RMSE) = 0.2106953329822997
coefficient of determination (R2) = 0.7123462478163505
